#!/bin/sh

dbus-update-activation-environment DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP 2>/dev/null
dex --autostart --environment i3

[ -x "$HOME/.screenlayout/screens.sh" ] && "$HOME/.screenlayout/screens.sh"

pgrep -x xss-lock >/dev/null || xss-lock --transfer-sleep-lock -- "$HOME/.config/rofi/modes/locker" --nofork &
