#!/bin/sh
set -eu

# tags: #pkg

sudo xbps-install -Sy curl python3-gobject gtk4 libadwaita libmanette

VERSION="2.4.2"
RELEASE="1"
APPIMAGE="Faugus-${VERSION}-${RELEASE}-x86_64.AppImage"
CHECKSUM="cff0ff05bf66dd934eab942eecf50b3a09a3d0be86186546132d687bc60c40b4"
INSTALL_DIR="/opt"
BIN_LINK="/usr/local/bin/faugus"
URL="https://github.com/Faugus/faugus-launcher/releases/download/${VERSION}/${APPIMAGE}"
TARGET_BIN="${INSTALL_DIR}/${APPIMAGE}"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

cd "$TMP_DIR"

curl -fL -o "$APPIMAGE" "$URL"
printf '%s  %s\n' "$CHECKSUM" "$APPIMAGE" | sha256sum --check

sudo rm -f "$TARGET_BIN"
sudo mv "$APPIMAGE" "$TARGET_BIN"
sudo chmod +x "$TARGET_BIN"

sudo ln -sfn "$TARGET_BIN" "$BIN_LINK"

echo "Faugus installed: $BIN_LINK -> $TARGET_BIN"
