#!/bin/sh
set -eu

# tags: #app

add_root="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

command -v flatpak >/dev/null 2>&1 || { echo "flatpak is not installed. Run add/flathub first."; exit 1; }

sudo xbps-install -Sy \
    borg \
    gucharmap \
    xournalpp \
    gpick \
    mpv \
    nsxiv \
    obs \
    calibre \
    zathura \
    zathura-cb \
    zathura-djvu \
    zathura-pdf-poppler

flatpak install -y flathub com.github.tchx84.Flatseal
flatpak install -y flathub com.borgbase.Vorta
flatpak install flathub org.libreoffice.LibreOffice
flatpak run com.protonvpn.www

"$add_root/firefox"
"$add_root/emacs"
"$add_root/printers"
