#!/bin/sh
set -eu

# tags: #pkg

sudo xbps-install -Sy curl

VERSION="0.18.1.1"
APPIMAGE="helium-${VERSION}-x86_64.AppImage"
CHECKSUM="d1e1b993dfbfee06e9f90e8a29cd58e87a475197b04fc0487506227c338569cb"
INSTALL_DIR="/opt"
BIN_LINK="/usr/local/bin/helium"
URL="https://github.com/imputnet/helium-linux/releases/download/${VERSION}/${APPIMAGE}"
TARGET_BIN="${INSTALL_DIR}/${APPIMAGE}"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

cd "$TMP_DIR"

curl -fL -o "$APPIMAGE" "$URL"
printf '%s  %s\n' "$CHECKSUM" "$APPIMAGE" | sha256sum --check

sudo rm -f "$TARGET_BIN"
sudo mv "$APPIMAGE" "$TARGET_BIN"
sudo chmod +x "$TARGET_BIN"

sudo ln -sfn "$TARGET_BIN" "$BIN_LINK"

echo "Helium installed: $BIN_LINK -> $TARGET_BIN"
