#!/bin/sh
set -eu

# tags: #dev

add_root="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

sudo xbps-install -Sy openjdk25

printf 'Install SDKMAN? [y/N]: '
read -r choice

case "$choice" in
    y|Y|yes|YES)
        sudo xbps-install -Sy curl unzip zip

        INSTALLER="sdkman-init.sh"
        CHECKSUM="b6f4fb257b420c7291c35549ae714af6d5af290bb8d57c219918f1f3d3d3e052"
        URL="https://get.sdkman.io"

        TMP_DIR="$(mktemp -d)"
        trap 'rm -rf "$TMP_DIR"' EXIT

        cd "$TMP_DIR"

        curl -fL -o "$INSTALLER" "$URL"
        printf '%s  %s\n' "$CHECKSUM" "$INSTALLER" | sha256sum --check
        bash "$INSTALLER"

        . "$HOME/.sdkman/bin/sdkman-init.sh"
        ;;
esac
