#!/bin/sh
set -eu

# tags: #pkg

command -v flatpak >/dev/null 2>&1 || { echo "flatpak is not installed. Run add/flathub first."; exit 1; }

add_root="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

"$add_root/wayvr"

flatpak install flathub io.github.wivrn.wivrn

sudo ln -sfn /etc/sv/avahi-daemon /var/service/avahi-daemon

sudo sv up avahi-daemon

sudo usermod -aG plugdev "$USER"

echo "For wired connection please do the following:"
echo "> adb reverse tcp:9757 tcp:9757"
echo "> adb shell am start -a android.intent.action.VIEW -d "wivrn+tcp://localhost" org.meumeu.wivrn"
