#!/bin/sh
set -eu

# tags: #pkg

add_root="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

sudo xbps-install -Sy \
    base-devel \
    clang \
    cmake \
    ncurses-term \
    tmux

"$add_root/shell"
"$add_root/nvim"
"$add_root/node"
"$add_root/codeberg"
